
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["gunicorn", "api.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120"]
    volumes:
      - .:/app
    env_file:
      - .env-dev
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  postgres-db-network:

volumes:
  postgres_data:
